/**
 * ⚠️ DEPRECATED: This file contains mock/test data and should NOT be used in production.
 * 
 * If you're seeing this file being imported, it's likely from legacy code.
 * All data should come from the backend API endpoints:
 * - /api/auth/me - Current user
 * - /api/users/{id} - Other users  
 * - /api/users/me/suggestions - User suggestions
 * 
 * To clean up: Remove imports of currentUser and peopleSeed from all components.
 * This file will be deleted in the next release.
 */

// DEPRECATED - DO NOT USE
export const currentUser = null;

// DEPRECATED - DO NOT USE  
export const peopleSeed = [];
    avatar: 'https://images.pexels.com/photos/37148308/pexels-photo-37148308.jpeg',
    cover: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72',
    mutual: 14,
    verified: false,
  },
  {
    id: 'u4',
    name: 'Marcus Johnson',
    headline: 'Engineering Manager · Hiring across the team',
    avatar: 'https://images.unsplash.com/photo-1627161683077-e34782c24d81',
    cover: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c',
    mutual: 8,
    verified: true,
  },
  {
    id: 'u5',
    name: 'Elena Rodriguez',
    headline: 'Data Scientist @ Netflix | ML, A/B testing',
    avatar: 'https://images.pexels.com/photos/29852895/pexels-photo-29852895.jpeg',
    cover: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174',
    mutual: 47,
    verified: false,
  },
  {
    id: 'u6',
    name: 'David Park',
    headline: 'Founder & CEO at LaunchPad | Y Combinator W22',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
    cover: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab',
    mutual: 102,
    verified: true,
  },
  {
    id: 'u7',
    name: 'Layla Ahmed',
    headline: 'Marketing Lead · Storyteller · Growth Hacker',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956',
    cover: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72',
    mutual: 19,
    verified: false,
  },
  {
    id: 'u8',
    name: 'Robert Williams',
    headline: 'Cybersecurity Specialist | CISSP | OSCP',
    avatar: 'https://images.unsplash.com/photo-1506863530036-1efeddceb993',
    cover: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2',
    mutual: 5,
    verified: false,
  },
  {
    id: 'u9',
    name: 'Aisha Khan',
    headline: 'iOS Developer | Swift, SwiftUI enthusiast',
    avatar: 'https://images.pexels.com/photos/28442317/pexels-photo-28442317.jpeg',
    cover: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c',
    mutual: 28,
    verified: false,
  },
  {
    id: 'u10',
    name: 'Nathan Brooks',
    headline: 'Talent Acquisition · Tech Recruiting · Hiring!',
    avatar: 'https://images.pexels.com/photos/28513051/pexels-photo-28513051.jpeg',
    cover: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab',
    mutual: 64,
    verified: false,
  },
];

export const initialPosts = [
  {
    id: 'p1',
    author: peopleSeed[0],
    timeAgo: '2h',
    visibility: 'Anyone',
    content:
      "Just shipped a major feature that lets users collaborate in real-time across teams. Took 6 months of work from an amazing team. Proud of what we built together! \n\nKey lessons:\n• Ship small, iterate fast\n• Talk to users every single week\n• Engineering excellence compounds\n\nWhat's the biggest thing you shipped this quarter?",
    image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952',
    likes: 1247,
    comments: 89,
    reposts: 34,
    liked: false,
  },
  {
    id: 'p2',
    author: peopleSeed[5],
    timeAgo: '5h',
    visibility: 'Anyone',
    content:
      "We're hiring! 🚀 LaunchPad is opening 12 new roles across engineering, design, and growth. Fully remote, competitive equity, real ownership.\n\nIf you want to build the future of AI-powered productivity, DM me. Referrals welcomed.",
    image: null,
    likes: 532,
    comments: 47,
    reposts: 21,
    liked: false,
  },
  {
    id: 'p3',
    author: peopleSeed[2],
    timeAgo: '8h',
    visibility: 'Anyone',
    content:
      "Unpopular opinion: most design systems fail not because of bad components, but because nobody documents the WHY. \n\nPrinciples > Components.",
    image: 'https://images.unsplash.com/photo-1606857521015-7f9fcf423740',
    likes: 821,
    comments: 134,
    reposts: 56,
    liked: false,
  },
  {
    id: 'p4',
    author: peopleSeed[1],
    timeAgo: '1d',
    visibility: 'Anyone',
    content:
      "After 4 years at Stripe, here are the top 5 things I learned about distributed systems:\n\n1. Idempotency is your best friend\n2. Observability > Monitoring\n3. Async is the default, not the exception\n4. Backpressure saves lives\n5. Test in production (responsibly)\n\nSave this for later.",
    image: null,
    likes: 2104,
    comments: 187,
    reposts: 412,
    liked: true,
  },
  {
    id: 'p5',
    author: peopleSeed[4],
    timeAgo: '1d',
    visibility: 'Anyone',
    content:
      "Speaking at the AI Summit next week about how we use ML to personalize recommendations for 250M+ subscribers. If you're attending, let's grab coffee!",
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04',
    likes: 689,
    comments: 54,
    reposts: 18,
    liked: false,
  },
  {
    id: 'p6',
    author: peopleSeed[3],
    timeAgo: '2d',
    visibility: 'Anyone',
    content:
      "Hot take: the best engineers I've ever managed are the ones who write the most boring code. Boring = predictable = maintainable = scalable. Stop trying to be clever.",
    image: null,
    likes: 1532,
    comments: 211,
    reposts: 87,
    liked: false,
  },
];

export const initialComments = {
  p1: [
    {
      id: 'c1',
      author: peopleSeed[1],
      text: 'Huge congrats Sarah! The real-time sync was buttery smooth when I tried it.',
      timeAgo: '1h',
      likes: 12,
    },
    {
      id: 'c2',
      author: peopleSeed[2],
      text: 'Inspiring. Love the iteration mindset 👏',
      timeAgo: '45m',
      likes: 5,
    },
  ],
  p4: [
    {
      id: 'c3',
      author: peopleSeed[5],
      text: 'Saved. Backpressure is so underrated.',
      timeAgo: '20h',
      likes: 34,
    },
  ],
};

export const jobsData = [
  {
    id: 'j1',
    title: 'Senior Frontend Engineer',
    company: 'Stripe',
    logo: 'https://logo.clearbit.com/stripe.com',
    location: 'San Francisco, CA (Hybrid)',
    postedAgo: '2 days ago',
    applicants: 87,
    salary: '$180K - $260K',
    type: 'Full-time',
    easyApply: true,
    promoted: true,
    description:
      'Build delightful payment experiences used by millions. Work with React, TypeScript, and the latest web platform APIs.',
    skills: ['React', 'TypeScript', 'GraphQL', 'CSS'],
  },
  {
    id: 'j2',
    title: 'Staff Software Engineer, Platform',
    company: 'Airbnb',
    logo: 'https://logo.clearbit.com/airbnb.com',
    location: 'Remote',
    postedAgo: '1 day ago',
    applicants: 134,
    salary: '$220K - $310K',
    type: 'Full-time',
    easyApply: true,
    promoted: false,
    description: 'Lead architectural decisions for the booking platform serving 4M+ hosts globally.',
    skills: ['Java', 'Kubernetes', 'AWS', 'System Design'],
  },
  {
    id: 'j3',
    title: 'Product Designer',
    company: 'Figma',
    logo: 'https://logo.clearbit.com/figma.com',
    location: 'New York, NY',
    postedAgo: '5 hours ago',
    applicants: 24,
    salary: '$150K - $200K',
    type: 'Full-time',
    easyApply: false,
    promoted: true,
    description: 'Shape the future of collaborative design tools. Work alongside the best in the industry.',
    skills: ['Figma', 'Prototyping', 'Design Systems'],
  },
  {
    id: 'j4',
    title: 'Engineering Manager',
    company: 'Notion',
    logo: 'https://logo.clearbit.com/notion.so',
    location: 'San Francisco, CA',
    postedAgo: '3 days ago',
    applicants: 56,
    salary: '$240K - $340K',
    type: 'Full-time',
    easyApply: true,
    promoted: false,
    description: 'Lead a team of 8 engineers building real-time collaboration features.',
    skills: ['Leadership', 'React', 'CRDT', 'Mentoring'],
  },
  {
    id: 'j5',
    title: 'Backend Engineer',
    company: 'Vercel',
    logo: 'https://logo.clearbit.com/vercel.com',
    location: 'Remote',
    postedAgo: '1 week ago',
    applicants: 312,
    salary: '$160K - $230K',
    type: 'Full-time',
    easyApply: true,
    promoted: false,
    description: 'Help build the platform powering the modern web. Edge computing, serverless, the works.',
    skills: ['Go', 'Rust', 'Distributed Systems'],
  },
  {
    id: 'j6',
    title: 'Data Scientist',
    company: 'OpenAI',
    logo: 'https://logo.clearbit.com/openai.com',
    location: 'San Francisco, CA',
    postedAgo: '12 hours ago',
    applicants: 198,
    salary: '$200K - $300K',
    type: 'Full-time',
    easyApply: false,
    promoted: true,
    description: 'Work on the data foundations powering frontier AI models.',
    skills: ['Python', 'ML', 'Statistics', 'SQL'],
  },
  {
    id: 'j7',
    title: 'iOS Engineer',
    company: 'Apple',
    logo: 'https://logo.clearbit.com/apple.com',
    location: 'Cupertino, CA',
    postedAgo: '4 days ago',
    applicants: 78,
    salary: '$170K - $250K',
    type: 'Full-time',
    easyApply: false,
    promoted: false,
    description: 'Build the apps shipped to a billion devices. SwiftUI, Swift Concurrency, the future of iOS.',
    skills: ['Swift', 'SwiftUI', 'iOS', 'UIKit'],
  },
  {
    id: 'j8',
    title: 'DevRel Engineer',
    company: 'GitHub',
    logo: 'https://logo.clearbit.com/github.com',
    location: 'Remote',
    postedAgo: '6 days ago',
    applicants: 145,
    salary: '$140K - $190K',
    type: 'Full-time',
    easyApply: true,
    promoted: false,
    description: 'Be the voice of the developer community. Write, speak, code, repeat.',
    skills: ['Public Speaking', 'Writing', 'Open Source'],
  },
];

export const notificationsData = [
  {
    id: 'n1',
    actor: peopleSeed[0],
    type: 'like',
    text: 'liked your post about scaling React applications',
    timeAgo: '5m',
    read: false,
  },
  {
    id: 'n2',
    actor: peopleSeed[3],
    type: 'connection',
    text: 'accepted your connection request',
    timeAgo: '1h',
    read: false,
  },
  {
    id: 'n3',
    actor: peopleSeed[5],
    type: 'mention',
    text: 'mentioned you in a post',
    timeAgo: '3h',
    read: false,
  },
  {
    id: 'n4',
    actor: peopleSeed[2],
    type: 'comment',
    text: 'commented on your post: "This is brilliant work!"',
    timeAgo: '5h',
    read: true,
  },
  {
    id: 'n5',
    actor: peopleSeed[6],
    type: 'birthday',
    text: "is celebrating a work anniversary today — 5 years at her current role",
    timeAgo: '8h',
    read: true,
  },
  {
    id: 'n6',
    actor: peopleSeed[1],
    type: 'job',
    text: 'shared a job that matches your profile: Staff Engineer at Stripe',
    timeAgo: '1d',
    read: true,
  },
  {
    id: 'n7',
    actor: peopleSeed[7],
    type: 'like',
    text: 'and 12 others liked your comment',
    timeAgo: '2d',
    read: true,
  },
];

export const messagesData = [
  {
    id: 'm1',
    user: peopleSeed[0],
    lastMessage: "Sounds great! Let's hop on a call tomorrow at 3pm PST.",
    timeAgo: '12m',
    unread: true,
    online: true,
    thread: [
      { id: 't1', from: 'them', text: 'Hey Ahmed! Saw your post on real-time systems — really insightful.', time: '10:42 AM' },
      { id: 't2', from: 'me', text: "Thanks Sarah! Glad it resonated. Are you working on something similar at Microsoft?", time: '10:45 AM' },
      { id: 't3', from: 'them', text: 'Yes! Actually, would love your perspective on our CRDT implementation. Got 20 mins this week?', time: '10:46 AM' },
      { id: 't4', from: 'me', text: 'Absolutely. Tomorrow works for me. What timezone are you in?', time: '10:50 AM' },
      { id: 't5', from: 'them', text: "Sounds great! Let's hop on a call tomorrow at 3pm PST.", time: '10:51 AM' },
    ],
  },
  {
    id: 'm2',
    user: peopleSeed[3],
    lastMessage: 'I just sent you the offer details. Let me know your thoughts.',
    timeAgo: '1h',
    unread: true,
    online: false,
    thread: [
      { id: 't1', from: 'them', text: "Hi Ahmed — really enjoyed our chat yesterday.", time: '9:00 AM' },
      { id: 't2', from: 'them', text: 'I just sent you the offer details. Let me know your thoughts.', time: '9:02 AM' },
    ],
  },
  {
    id: 'm3',
    user: peopleSeed[5],
    lastMessage: 'Would you be open to advising for us part-time?',
    timeAgo: '3h',
    unread: false,
    online: true,
    thread: [{ id: 't1', from: 'them', text: 'Would you be open to advising for us part-time?', time: 'Yesterday' }],
  },
  {
    id: 'm4',
    user: peopleSeed[1],
    lastMessage: 'Thanks for the intro — meeting went really well.',
    timeAgo: '1d',
    unread: false,
    online: false,
    thread: [{ id: 't1', from: 'them', text: 'Thanks for the intro — meeting went really well.', time: 'Mon' }],
  },
  {
    id: 'm5',
    user: peopleSeed[7],
    lastMessage: 'Sent the doc. LMK what you think.',
    timeAgo: '2d',
    unread: false,
    online: false,
    thread: [{ id: 't1', from: 'them', text: 'Sent the doc. LMK what you think.', time: 'Sun' }],
  },
];

export const newsData = [
  { id: 'nw1', title: 'AI startups raise record $50B in Q2', meta: '4h ago · 12,453 readers' },
  { id: 'nw2', title: 'Remote work plateaus across tech', meta: '6h ago · 8,221 readers' },
  { id: 'nw3', title: 'Why senior engineers are switching to fractional roles', meta: '1d ago · 5,109 readers' },
  { id: 'nw4', title: 'The death of the takehome interview?', meta: '1d ago · 14,322 readers' },
  { id: 'nw5', title: 'Apple Vision Pro hits 1M units', meta: '2d ago · 22,540 readers' },
];

export const initialInvitations = [
  { id: 'inv1', user: peopleSeed[6], note: 'Hi Ahmed — would love to connect, we have many mutuals!', mutual: peopleSeed[6].mutual },
  { id: 'inv2', user: peopleSeed[8], note: '', mutual: peopleSeed[8].mutual },
  { id: 'inv3', user: peopleSeed[9], note: 'Hi! Are you open to chatting about a Staff role at our client?', mutual: peopleSeed[9].mutual },
];